//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AVFramework.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class YaraScannerEntities : DbContext
    {
        public YaraScannerEntities()
            : base("name=YaraScannerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<actions> actions { get; set; }
        public virtual DbSet<administrators> administrators { get; set; }
        public virtual DbSet<computers> computers { get; set; }
        public virtual DbSet<events> events { get; set; }
        public virtual DbSet<viruses> viruses { get; set; }
        public virtual DbSet<viruses_types> viruses_types { get; set; }
    }
}
