//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AVFramework.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class VirusFound
    {
        public int Id { get; set; }
        public string ComputerName { get; set; }
        public string Ip { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public string RuleName { get; set; }
    }
}
